{
    "openapi": "3.0.0",
    "info": {
        "version": "1.0.0",
        "title": "API Docs - ERP",
        "description": "API Docs",
        "x-logo": {
            "url": "https://cdn.prod.website-files.com/6075c27738665c833a39fd83/608566aaabf4b474f887440f_Light.svg",
            "backgroundColor": "#000000",
            "altText": "Makini Logo"
        }
    },
    "servers": [
        {
            "url": "https://api.makini.io"
        }
    ],
    "paths": {
        "/api/erp/bom": {
            "post": {
                "description": "\n[Detail validations](docs/platform-validation.md)\n",
                "summary": "Create a BillOfMaterial ",
                "parameters": [],
                "tags": [
                    "BillOfMaterial"
                ],
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/components/schemas/BillOfMaterial"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "requestBody": {
                    "description": "Request body",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "siteKey": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "name": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "projectKey": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "type": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "lineItems": {
                                        "type": "object",
                                        "nullable": true,
                                        "properties": {
                                            "locationKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "materialKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "productKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "currencyKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "description": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "quantity": {
                                                "type": "nullable|number",
                                                "nullable": true,
                                                "format": "nullable|number"
                                            },
                                            "uomKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "notes": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "price": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            }
                                        }
                                    },
                                    "createdAt": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "updatedAt": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    }
                                },
                                "example": {
                                    "siteKey": "04000265145041",
                                    "name": "string",
                                    "projectKey": "04000140989048",
                                    "type": "string",
                                    "lineItems": [
                                        {
                                            "locationKey": "02000738763042",
                                            "materialKey": "06000478877593",
                                            "productKey": "00000275733778",
                                            "currencyKey": "07000482049375",
                                            "description": "Praesentium illum quo asperiores.",
                                            "quantity": "string",
                                            "uomKey": "09000222787700",
                                            "notes": "string",
                                            "price": "string"
                                        }
                                    ],
                                    "createdAt": "1990-06-19T08:24:39Z",
                                    "updatedAt": "2012-03-26T02:40:41Z"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/erp/receiving": {
            "post": {
                "description": "\n[Detail validations](docs/platform-validation.md)\n",
                "summary": "Create a Receiving ",
                "parameters": [],
                "tags": [
                    "Receiving"
                ],
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/components/schemas/Receiving"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "requestBody": {
                    "description": "Request body",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "siteKey": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "vendorKey": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "poKey": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "code": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "orderNo": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "orderDate": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "title": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "description": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "completedAt": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "shippingMethod": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "notes": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "currencyKey": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "totalNetValue": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "totalTaxValue": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "totalGrossValue": {
                                        "type": "string",
                                        "nullable": true,
                                        "format": "string"
                                    },
                                    "lineItems": {
                                        "type": "object",
                                        "nullable": true,
                                        "properties": {
                                            "locationKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "accountKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "vendorKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "assetKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "materialKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "productKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "statusKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "storeroomKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "lineNo": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "code": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "type": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "name": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "description": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "lineRef": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "quantity": {
                                                "type": "nullable|numeric",
                                                "nullable": true,
                                                "format": "nullable|numeric"
                                            },
                                            "receivedQuantity": {
                                                "type": "nullable|numeric",
                                                "nullable": true,
                                                "format": "nullable|numeric"
                                            },
                                            "uomKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "currencyKey": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "price": {
                                                "type": "nullable|numeric",
                                                "nullable": true,
                                                "format": "nullable|numeric"
                                            },
                                            "discount": {
                                                "type": "nullable|numeric",
                                                "nullable": true,
                                                "format": "nullable|numeric"
                                            },
                                            "lineTaxValue": {
                                                "type": "nullable|numeric",
                                                "nullable": true,
                                                "format": "nullable|numeric"
                                            },
                                            "lineTotalValue": {
                                                "type": "nullable|numeric",
                                                "nullable": true,
                                                "format": "nullable|numeric"
                                            },
                                            "notes": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "deliveryAt": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            },
                                            "dueAt": {
                                                "type": "string",
                                                "nullable": true,
                                                "format": "string"
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "siteKey": "09000288337623",
                                    "vendorKey": "02000418571022",
                                    "poKey": "05000109919009",
                                    "code": "88907222",
                                    "orderNo": "string",
                                    "orderDate": "2006-08-01T05:02:42Z",
                                    "title": "Dolores sunt eos beatae alias ut libero et.",
                                    "description": "Laboriosam qui et nisi ullam hic ut.",
                                    "completedAt": "2023-10-19T11:59:10Z",
                                    "shippingMethod": "string",
                                    "notes": "string",
                                    "currencyKey": "05000977397278",
                                    "totalNetValue": "string",
                                    "totalTaxValue": "string",
                                    "totalGrossValue": "string",
                                    "lineItems": [
                                        {
                                            "locationKey": "09000824705625",
                                            "accountKey": "07000125821663",
                                            "vendorKey": "00000297553204",
                                            "assetKey": "07000782527281",
                                            "materialKey": "02000554549588",
                                            "productKey": "08000350832403",
                                            "statusKey": "02000818481139",
                                            "storeroomKey": "03000384932826",
                                            "lineNo": "string",
                                            "code": "17448703",
                                            "type": "string",
                                            "name": "string",
                                            "description": "Necessitatibus libero itaque consectetur odio.",
                                            "lineRef": "string",
                                            "quantity": "string",
                                            "receivedQuantity": "string",
                                            "uomKey": "08000711466177",
                                            "currencyKey": "09000358100566",
                                            "price": "string",
                                            "discount": "string",
                                            "lineTaxValue": "string",
                                            "lineTotalValue": "string",
                                            "notes": "string",
                                            "deliveryAt": "1988-10-22T00:28:51Z",
                                            "dueAt": "2010-05-08T11:42:49Z"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        },
        "schemas": {
            "BillOfMaterialCollection": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/BillOfMaterial"
                }
            },
            "BOMLineItem": {
                "title": "BOMLineItem",
                "properties": {
                    "locationKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "materialKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "productKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "currencyKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "description": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "quantity": {
                        "type": "object",
                        "description": "Description",
                        "nullable": false,
                        "format": "object"
                    },
                    "uomKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "notes": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "price": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "createdAt": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "updatedAt": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    }
                },
                "example": {
                    "locationKey": "09000392010585",
                    "materialKey": "00000107779319",
                    "productKey": "01000264971694",
                    "currencyKey": "09000602926560",
                    "description": "Et sed illum ut.",
                    "quantity": "string",
                    "uomKey": "05000782270621",
                    "notes": "string",
                    "price": "string",
                    "createdAt": "2015-01-22T00:53:55Z",
                    "updatedAt": "1997-12-11T01:16:55Z"
                }
            },
            "BillOfMaterial": {
                "title": "BillOfMaterial",
                "properties": {
                    "key": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "siteKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "name": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "projectKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "type": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "lineItems": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/BOMLineItem"
                        }
                    },
                    "createdAt": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "updatedAt": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    }
                },
                "example": {
                    "key": "09000879756777",
                    "siteKey": "06000650427572",
                    "name": "string",
                    "projectKey": "05000263024447",
                    "type": "string",
                    "lineItems": [
                        {
                            "locationKey": "00000850685834",
                            "materialKey": "00000011512605",
                            "productKey": "01000505750680",
                            "currencyKey": "03000189056619",
                            "description": "Sed est totam ut.",
                            "quantity": "string",
                            "uomKey": "07000564580106",
                            "notes": "string",
                            "price": "string",
                            "createdAt": "1994-05-07T16:45:27Z",
                            "updatedAt": "1978-12-17T01:03:40Z"
                        }
                    ],
                    "createdAt": "2013-11-05T02:57:55Z",
                    "updatedAt": "1977-01-30T03:00:57Z"
                }
            },
            "ReceivingCollection": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/Receiving"
                }
            },
            "POLineItem": {
                "title": "POLineItem",
                "properties": {
                    "key": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "locationKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "accountKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "vendorKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "assetKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "materialKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "productKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "statusKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "storeroomKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "lineNo": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "code": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "type": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "name": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "description": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "lineRef": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "quantity": {
                        "type": "object",
                        "description": "Description",
                        "nullable": false,
                        "format": "object"
                    },
                    "receivedQuantity": {
                        "type": "object",
                        "description": "Description",
                        "nullable": false,
                        "format": "object"
                    },
                    "uomKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "currencyKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "price": {
                        "type": "object",
                        "description": "Description",
                        "nullable": false,
                        "format": "object"
                    },
                    "discount": {
                        "type": "object",
                        "description": "Description",
                        "nullable": false,
                        "format": "object"
                    },
                    "lineTaxValue": {
                        "type": "object",
                        "description": "Description",
                        "nullable": false,
                        "format": "object"
                    },
                    "lineTotalValue": {
                        "type": "object",
                        "description": "Description",
                        "nullable": false,
                        "format": "object"
                    },
                    "notes": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "deliveryAt": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "dueAt": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "createdAt": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "updatedAt": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "deletedAt": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    }
                },
                "example": {
                    "key": "07000603317425",
                    "locationKey": "01000821852053",
                    "accountKey": "06000533777211",
                    "vendorKey": "07000731079485",
                    "assetKey": "08000170331776",
                    "materialKey": "05000086316023",
                    "productKey": "04000188843240",
                    "statusKey": "06000336144029",
                    "storeroomKey": "07000449270697",
                    "lineNo": "string",
                    "code": "89917992",
                    "type": "string",
                    "name": "string",
                    "description": "Qui quisquam et ad quo nisi est.",
                    "lineRef": "string",
                    "quantity": "string",
                    "receivedQuantity": "string",
                    "uomKey": "06000456600128",
                    "currencyKey": "09000276495281",
                    "price": "string",
                    "discount": "string",
                    "lineTaxValue": "string",
                    "lineTotalValue": "string",
                    "notes": "string",
                    "deliveryAt": "1990-12-27T02:48:09Z",
                    "dueAt": "2015-02-12T11:54:12Z",
                    "createdAt": "1972-05-08T12:10:13Z",
                    "updatedAt": "1989-12-27T20:10:27Z",
                    "deletedAt": "1971-04-15T19:30:14Z"
                }
            },
            "Receiving": {
                "title": "Receiving",
                "properties": {
                    "key": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "organizationKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "siteKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "vendorKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "poKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "code": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "orderNo": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "orderDate": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "title": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "description": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "completedAt": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "shippingMethod": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "notes": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "currencyKey": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "totalNetValue": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "totalTaxValue": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "totalGrossValue": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "lineItems": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/POLineItem"
                        }
                    },
                    "createdAt": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    },
                    "updatedAt": {
                        "type": "string",
                        "description": "Description",
                        "nullable": false,
                        "format": "string"
                    }
                },
                "example": {
                    "key": "09000325341828",
                    "organizationKey": "09000576717509",
                    "siteKey": "00000920164198",
                    "vendorKey": "07000462648668",
                    "poKey": "05000660446190",
                    "code": "01809749",
                    "orderNo": "string",
                    "orderDate": "1983-10-06T04:50:51Z",
                    "title": "Totam ea doloremque dignissimos nisi aut.",
                    "description": "Adipisci corporis est minus repudiandae sed.",
                    "completedAt": "1991-01-15T16:56:56Z",
                    "shippingMethod": "string",
                    "notes": "string",
                    "currencyKey": "09000234699071",
                    "totalNetValue": "string",
                    "totalTaxValue": "string",
                    "totalGrossValue": "string",
                    "lineItems": [
                        {
                            "key": "01000748771164",
                            "locationKey": "06000094721212",
                            "accountKey": "08000332048511",
                            "vendorKey": "09000064725702",
                            "assetKey": "04000404615371",
                            "materialKey": "00000522908235",
                            "productKey": "03000306023137",
                            "statusKey": "07000001292932",
                            "storeroomKey": "03000121669769",
                            "lineNo": "string",
                            "code": "70193497",
                            "type": "string",
                            "name": "string",
                            "description": "Dolores commodi quod saepe iste vitae pariatur.",
                            "lineRef": "string",
                            "quantity": "string",
                            "receivedQuantity": "string",
                            "uomKey": "08000075246410",
                            "currencyKey": "08000875912267",
                            "price": "string",
                            "discount": "string",
                            "lineTaxValue": "string",
                            "lineTotalValue": "string",
                            "notes": "string",
                            "deliveryAt": "1980-02-15T04:12:29Z",
                            "dueAt": "1987-09-23T05:10:45Z",
                            "createdAt": "2024-12-23T11:09:42Z",
                            "updatedAt": "1997-02-16T19:07:33Z",
                            "deletedAt": "2006-12-29T19:36:01Z"
                        }
                    ],
                    "createdAt": "1974-06-20T10:15:36Z",
                    "updatedAt": "2012-07-31T06:42:17Z"
                }
            }
        }
    }
}